image: maven:3.9.6

stages: # List of stages for jobs and their order of execution
  - build
  - test
  - report
  - package

#.standard-rules:
#  rules:
#    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'  # Run for all changes to a merge request's source branch
#    - or:
#        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  # Run for pushes to default branch
#        - if: $CI_COMMIT_TAG  # Run for tagged commits

build-job:
  stage: build
  tags: 
    - backup
  script:
    - echo "Maven building started."
    - mvn -B -DskipTests clean package
  cache:
    paths:
    - "~/.m2/repository"

test-implemented-tests:
  stage: test
  tags: 
    - backup
  dependencies:
  - build-job
  script:
    - echo "Running all tests."
    - "echo TILEDATA_PATH='src/main/java/org/set/tileData.json' >> .env"
    - cat .env
    - mvn test

verify-job:
  stage: test
  tags: 
    - backup
  dependencies:
  - build-job
  script:
    - echo "Running additional verification tests."
    - "echo TILEDATA_PATH='src/main/java/org/set/tileData.json' >> .env"
    - cat .env
    - mvn verify

package-prod:
  stage: package
  tags: 
    - backup
  script:
  - echo "Maven package started"
  - mvn package
  environment: production
  rules:
  - if: $CI_COMMIT_BRANCH == "main"

sigridci:
  stage: report
  image:
    name: softwareimprovementgroup/sigridci:latest
  script:
  - sigridci.py --customer utst --system team04 --source .
  allow_failure: true
  artifacts:
    paths:
    - sigrid-ci-output/*
    reports:
      junit: sigrid-ci-output/sigridci-junit-format-report.xml
    expire_in: 1 week
    when: always
  rules:
    - if: $CI_MERGE_REQUEST_ID

sigridpublish:
  stage: report
  image:
    name: softwareimprovementgroup/sigridci
  script:
  - sigridci.py --customer utst --system team04 --source . --publish
  allow_failure: true
  artifacts:
    paths:
    - sigrid-ci-output/*
    expire_in: 1 week
    when: always
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

sast:
  stage: test
  tags: 
    - backup

include:
  - template: Security/SAST.gitlab-ci.yml

#variables:
#   DEPLOY_SERVER: "your-deploy-server.com"
#   DEPLOY_USER: "username"
#   DEPLOY_PASSWORD: "${CI_JOB_TOKEN}"
