image: maven:3.9.6

stages: # List of stages for jobs and their order of execution
  - build
  - test
  - report
  - package

build-job:
  stage: build
  tags:
  - SET2024
  script:
  - echo "Maven building started."
  - mvn -B -DskipTests clean package
  cache:
    paths:
    - "~/.m2/repository"

test-implemented-tests:
  stage: test
  tags:
  - SET2024
  dependencies:
  - build-job
  script:
  - echo "Running all tests."
  - mvn test

verify-job:
  stage: test
  tags:
  - SET2024
  dependencies:
  - build-job
  script:
  - echo "Running additional verification tests."
  - mvn verify

package-prod:
  stage: package
  tags:
  - SET2024
  script:
  - echo "Maven package started"
  - mvn package
  environment: production
  rules:
  - if: $CI_COMMIT_BRANCH == "main"

sigridci:
  stage: report
  image:
    name: softwareimprovementgroup/sigridci:latest
  script:
  - sigridci.py --customer utst --system team04 --source .
  allow_failure: true
  artifacts:
    paths:
    - sigrid-ci-output/*
    reports:
      junit: sigrid-ci-output/sigridci-junit-format-report.xml
    expire_in: 1 week
    when: always
  tags:
  - SET2024

sigridpublish:
  stage: report
  image:
    name: softwareimprovementgroup/sigridci
  script:
  - sigridci.py --customer utst --system team04 --source . --publish
  allow_failure: true
  artifacts:
    paths:
    - sigrid-ci-output/*
    expire_in: 1 week
    when: always
  tags:
  - SET2024
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

sast:
  stage: test
  tags:
  - SET2024

include:
  - template: Security/SAST.gitlab-ci.yml