stages: # List of stages for jobs and their order of execution
  - build
  - test
  - package
  - deploy

.standard-rules:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'  # Run for all changes to a merge request's source branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH       # Run for all changes to the default branch

build-job:
  stage: build
  tags:
    - SET2024
  script:
    - echo "Maven building started."
    - "mvn -B -DskipTests clean package"
    #- "mvn compile"

test-job:
  stage: test
  tags:
    - SET2024
  dependencies:
    - build-job
  script:
    - echo "This job tests something"
    - "mvn test"

test-new-tests:
  stage: test
  tags:
    - SET2024
  dependencies:
    - build-job
  script:
    - echo "Testing"
    - "mvn -Dtest=TestApp1 test"
  allow_failure: true
  # rules:
    # - if: $CI_COMMIT_REF_NAME == 'test'

verify-job:
  stage: test
  tags:
    - SET2024
  dependencies:
   - build-job
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - "mvn verify"
  # rules:
    # - if: $CI_COMMIT_REF_NAME !~ test

package-prod:
  stage: package
  tags:
    - SET2024
  script:
    - echo "Maven package started"
    - "mvn package"
  environment: production

deploy-prod:
  stage: deploy
  tags:
    - SET2024
  dependencies:
    - package-prod
  script:
    - echo "Maven deploy started"
    - "mvn deploy"
  environment: production
