# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: maven:latest
stages:
- build
- test
- report
build-job:
  stage: build
  tags:
  - SET2024
  script:
  - echo "Maven building started."
  - mvn -B -DskipTests clean package
  cache:
    paths:
    - "~/.m2/repository"
test-implemented-tests:
  stage: test
  tags:
  - SET2024
  dependencies:
  - build-job
  script:
  - echo "Running all tests."
  - mvn test -Dtest="*Implemented"
test-new-tests:
  stage: test
  tags:
  - SET2024
  dependencies:
  - build-job
  script:
  - echo "Testing"
  - mvn test -Dtest="*New"
  allow_failure: true
  rules:
  - if: "$CI_COMMIT_MESSAGE =~ /test/"
verify-job:
  stage: test
  tags:
  - SET2024
  dependencies:
  - build-job
  script:
  - echo "Running additional verification tests."
  - mvn verify
  rules:
  - if: $CI_COMMIT_BRANCH == "main"
sigridci:
  stage: report
  image:
    name: softwareimprovementgroup/sigridci:latest
  script:
  - sigridci.py --customer utst --system team04 --source .
  allow_failure: true
  artifacts:
    paths:
    - sigrid-ci-output/*
    reports:
      junit: sigrid-ci-output/sigridci-junit-format-report.xml
    expire_in: 1 week
    when: always
sigridpublish:
  stage: report
  image:
    name: softwareimprovementgroup/sigridci
  script:
  - sigridci.py --customer utst --system team04 --source . --publish
  allow_failure: true
  artifacts:
    paths:
    - sigrid-ci-output/*
    expire_in: 1 week
    when: always
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
